#!/bin/bash
set -x



OI=/var/lib/openinfoman
USERNAME=oi
BASEX=$OI/bin/basex


REPOS=("openinfoman-anon.xqm")
SFS=("stored_updating_query_definitions/wiki-star-bible.xml")

for REPO in ${REPOS[@]}
do
   INST="REPO INSTALL ${OI}/repo-src/${REPO}"
   $BASEX -Vc "${INST}"
done

for SF in ${SFS[@]}
do
  cd $OI
  $OI/resources/scripts/install_stored_function.php $OI/resources/$SF 
  if [[ $? != 0 ]]; then exit 1; fi
done


chown -R $USERNAME:$USERNAME $OI


